<a href="https://colab.research.google.com/github/AbbasAli01/Machine-Learning-Projects/blob/main/Adult_Income_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import pandas as pd

In [53]:
df = pd.read_csv('adult.csv')

In [54]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [55]:
df.shape

(48842, 15)

In [56]:
df.dtypes

age                 int64
workclass          object
fnlwgt              int64
education          object
educational-num     int64
marital-status     object
occupation         object
relationship       object
race               object
gender             object
capital-gain        int64
capital-loss        int64
hours-per-week      int64
native-country     object
income             object
dtype: object

In [57]:
df.nunique()

age                   74
workclass              9
fnlwgt             28523
education             16
educational-num       16
marital-status         7
occupation            15
relationship           6
race                   5
gender                 2
capital-gain         123
capital-loss          99
hours-per-week        96
native-country        42
income                 2
dtype: int64

In [58]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [59]:
cat_cols = [col for col in df.columns if df[col].dtype == 'object']
num_cols = [col for col in df.columns if df[col].dtype != 'object']

In [60]:
df[cat_cols].nunique()

workclass          9
education         16
marital-status     7
occupation        15
relationship       6
race               5
gender             2
native-country    42
income             2
dtype: int64

In [61]:
df['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [62]:
for col in cat_cols:
  print(f'{col}: {df[col].unique()}')
  print('-----------')

workclass: ['Private' 'Local-gov' '?' 'Self-emp-not-inc' 'Federal-gov' 'State-gov'
 'Self-emp-inc' 'Without-pay' 'Never-worked']
-----------
education: ['11th' 'HS-grad' 'Assoc-acdm' 'Some-college' '10th' 'Prof-school'
 '7th-8th' 'Bachelors' 'Masters' 'Doctorate' '5th-6th' 'Assoc-voc' '9th'
 '12th' '1st-4th' 'Preschool']
-----------
marital-status: ['Never-married' 'Married-civ-spouse' 'Widowed' 'Divorced' 'Separated'
 'Married-spouse-absent' 'Married-AF-spouse']
-----------
occupation: ['Machine-op-inspct' 'Farming-fishing' 'Protective-serv' '?'
 'Other-service' 'Prof-specialty' 'Craft-repair' 'Adm-clerical'
 'Exec-managerial' 'Tech-support' 'Sales' 'Priv-house-serv'
 'Transport-moving' 'Handlers-cleaners' 'Armed-Forces']
-----------
relationship: ['Own-child' 'Husband' 'Not-in-family' 'Unmarried' 'Wife' 'Other-relative']
-----------
race: ['Black' 'White' 'Asian-Pac-Islander' 'Other' 'Amer-Indian-Eskimo']
-----------
gender: ['Male' 'Female']
-----------
native-country: ['United-States' '?' 'Peru' 'Guatemala' 'Mexico' 'Dominican-Republic'
 'Ireland' 'Germany' 'Philippines' 'Thailand' 'Haiti' 'El-Salvador'
 'Puerto-Rico' 'Vietnam' 'South' 'Columbia' 'Japan' 'India' 'Cambodia'
 'Poland' 'Laos' 'England' 'Cuba' 'Taiwan' 'Italy' 'Canada' 'Portugal'
 'China' 'Nicaragua' 'Honduras' 'Iran' 'Scotland' 'Jamaica' 'Ecuador'
 'Yugoslavia' 'Hungary' 'Hong' 'Greece' 'Trinadad&Tobago'
 'Outlying-US(Guam-USVI-etc)' 'France' 'Holand-Netherlands']
-----------
income: ['<=50K' '>50K']
-----------

In [63]:
for col in cat_cols:
  if '?' in df[col].unique():
    print(col)

workclass
occupation
native-country

In [64]:
df['occupation'].value_counts().get('?', 0), df['workclass'].value_counts().get('?', 0), df['native-country'].value_counts().get('?', 0)

(2809, 2799, 857)

In [65]:
df = df[(df['occupation'] != '?') & (df['workclass'] != '?') & (df['native-country'] != '?')]

In [66]:
df.shape

(45222, 15)

In [67]:
for col in cat_cols:
  if '?' in df[col].unique():
    print(col)

In [68]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
5,34,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K

In [69]:
df[cat_cols].nunique().sort_values()

gender             2
income             2
race               5
relationship       6
workclass          7
marital-status     7
occupation        14
education         16
native-country    41
dtype: int64

In [70]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['gender'] = le.fit_transform(df['gender'])
df['income'] = le.fit_transform(df['income'])

In [72]:
df = pd.get_dummies(df, columns=['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race'])

In [100]:
df.shape

(45222, 64)

In [73]:
pd.set_option('display.max_columns', None)
df.head()

,age,fnlwgt,educational-num,gender,capital-gain,capital-loss,hours-per-week,native-country,income,workclass_Federal-gov,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,education_10th,education_11th,education_12th,education_1st-4th,education_5th-6th,education_7th-8th,education_9th,education_Assoc-acdm,education_Assoc-voc,education_Bachelors,education_Doctorate,education_HS-grad,education_Masters,education_Preschool,education_Prof-school,education_Some-college,marital-status_Divorced,marital-status_Married-AF-spouse,marital-status_Married-civ-spouse,marital-status_Married-spouse-absent,marital-status_Never-married,marital-status_Separated,marital-status_Widowed,occupation_Adm-clerical,occupation_Armed-Forces,occupation_Craft-repair,occupation_Exec-managerial,occupation_Farming-fishing,occupation_Handlers-cleaners,occupation_Machine-op-inspct,occupation_Other-service,occupation_Priv-house-serv,occupation_Prof-specialty,occupation_Protective-serv,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,relationship_Husband,relationship_Not-in-family,relationship_Other-relative,relationship_Own-child,relationship_Unmarried,relationship_Wife,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,25,226802,7,1,0,0,40,United-States,0,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False
1,38,89814,9,1,0,0,50,United-States,0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
2,28,336951,12,1,0,0,40,United-States,1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True
3,44,160323,10,1,7688,0,40,United-States,1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False
5,34,198693,6,1,0,0,30,United-States,0,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True

In [74]:
bool_col = [col for col in df.columns if df[col].dtype == 'bool']

In [75]:
df[bool_col] = df[bool_col].astype(int)

In [76]:
df.head()

,age,fnlwgt,educational-num,gender,capital-gain,capital-loss,hours-per-week,native-country,income,workclass_Federal-gov,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,education_10th,education_11th,education_12th,education_1st-4th,education_5th-6th,education_7th-8th,education_9th,education_Assoc-acdm,education_Assoc-voc,education_Bachelors,education_Doctorate,education_HS-grad,education_Masters,education_Preschool,education_Prof-school,education_Some-college,marital-status_Divorced,marital-status_Married-AF-spouse,marital-status_Married-civ-spouse,marital-status_Married-spouse-absent,marital-status_Never-married,marital-status_Separated,marital-status_Widowed,occupation_Adm-clerical,occupation_Armed-Forces,occupation_Craft-repair,occupation_Exec-managerial,occupation_Farming-fishing,occupation_Handlers-cleaners,occupation_Machine-op-inspct,occupation_Other-service,occupation_Priv-house-serv,occupation_Prof-specialty,occupation_Protective-serv,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,relationship_Husband,relationship_Not-in-family,relationship_Other-relative,relationship_Own-child,relationship_Unmarried,relationship_Wife,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,25,226802,7,1,0,0,40,United-States,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
1,38,89814,9,1,0,0,50,United-States,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
2,28,336951,12,1,0,0,40,United-States,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1
3,44,160323,10,1,7688,0,40,United-States,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
5,34,198693,6,1,0,0,30,United-States,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1

In [78]:
frequency_encoding = df['native-country'].value_counts().to_dict()

In [79]:
frequency_encoding

{'United-States': 41292,
 'Mexico': 903,
 'Philippines': 283,
 'Germany': 193,
 'Puerto-Rico': 175,
 'Canada': 163,
 'El-Salvador': 147,
 'India': 147,
 'Cuba': 133,
 'England': 119,
 'China': 113,
 'Jamaica': 103,
 'South': 101,
 'Italy': 100,
 'Dominican-Republic': 97,
 'Japan': 89,
 'Guatemala': 86,
 'Vietnam': 83,
 'Columbia': 82,
 'Poland': 81,
 'Haiti': 69,
 'Portugal': 62,
 'Iran': 56,
 'Taiwan': 55,
 'Greece': 49,
 'Nicaragua': 48,
 'Peru': 45,
 'Ecuador': 43,
 'France': 36,
 'Ireland': 36,
 'Thailand': 29,
 'Hong': 28,
 'Cambodia': 26,
 'Trinadad&Tobago': 26,
 'Yugoslavia': 23,
 'Outlying-US(Guam-USVI-etc)': 22,
 'Laos': 21,
 'Scotland': 20,
 'Honduras': 19,
 'Hungary': 18,
 'Holand-Netherlands': 1}

In [80]:
df['native-country'] = df['native-country'].map(frequency_encoding)

In [81]:
df.head()

,age,fnlwgt,educational-num,gender,capital-gain,capital-loss,hours-per-week,native-country,income,workclass_Federal-gov,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,education_10th,education_11th,education_12th,education_1st-4th,education_5th-6th,education_7th-8th,education_9th,education_Assoc-acdm,education_Assoc-voc,education_Bachelors,education_Doctorate,education_HS-grad,education_Masters,education_Preschool,education_Prof-school,education_Some-college,marital-status_Divorced,marital-status_Married-AF-spouse,marital-status_Married-civ-spouse,marital-status_Married-spouse-absent,marital-status_Never-married,marital-status_Separated,marital-status_Widowed,occupation_Adm-clerical,occupation_Armed-Forces,occupation_Craft-repair,occupation_Exec-managerial,occupation_Farming-fishing,occupation_Handlers-cleaners,occupation_Machine-op-inspct,occupation_Other-service,occupation_Priv-house-serv,occupation_Prof-specialty,occupation_Protective-serv,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,relationship_Husband,relationship_Not-in-family,relationship_Other-relative,relationship_Own-child,relationship_Unmarried,relationship_Wife,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,25,226802,7,1,0,0,40,41292,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
1,38,89814,9,1,0,0,50,41292,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
2,28,336951,12,1,0,0,40,41292,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1
3,44,160323,10,1,7688,0,40,41292,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
5,34,198693,6,1,0,0,30,41292,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1

In [83]:
pd.set_option('display.max_rows', None)
df.dtypes

age                                     int64
fnlwgt                                  int64
educational-num                         int64
gender                                  int64
capital-gain                            int64
capital-loss                            int64
hours-per-week                          int64
native-country                          int64
income                                  int64
workclass_Federal-gov                   int64
workclass_Local-gov                     int64
workclass_Private                       int64
workclass_Self-emp-inc                  int64
workclass_Self-emp-not-inc              int64
workclass_State-gov                     int64
workclass_Without-pay                   int64
education_10th                          int64
education_11th                          int64
education_12th                          int64
education_1st-4th                       int64
education_5th-6th                       int64
education_7th-8th                       int64
education_9th                           int64
education_Assoc-acdm                    int64
education_Assoc-voc                     int64
education_Bachelors                     int64
education_Doctorate                     int64
education_HS-grad                       int64
education_Masters                       int64
education_Preschool                     int64
education_Prof-school                   int64
education_Some-college                  int64
marital-status_Divorced                 int64
marital-status_Married-AF-spouse        int64
marital-status_Married-civ-spouse       int64
marital-status_Married-spouse-absent    int64
marital-status_Never-married            int64
marital-status_Separated                int64
marital-status_Widowed                  int64
occupation_Adm-clerical                 int64
occupation_Armed-Forces                 int64
occupation_Craft-repair                 int64
occupation_Exec-managerial              int64
occupation_Farming-fishing              int64
occupation_Handlers-cleaners            int64
occupation_Machine-op-inspct            int64
occupation_Other-service                int64
occupation_Priv-house-serv              int64
occupation_Prof-specialty               int64
occupation_Protective-serv              int64
occupation_Sales                        int64
occupation_Tech-support                 int64
occupation_Transport-moving             int64
relationship_Husband                    int64
relationship_Not-in-family              int64
relationship_Other-relative             int64
relationship_Own-child                  int64
relationship_Unmarried                  int64
relationship_Wife                       int64
race_Amer-Indian-Eskimo                 int64
race_Asian-Pac-Islander                 int64
race_Black                              int64
race_Other                              int64
race_White                              int64
dtype: object

In [84]:
from sklearn.model_selection import train_test_split

X = df.drop('income', axis=1)
y = df['income']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [85]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)
dtc_prediction = dtc.predict(X_test)

In [86]:
dtc_prediction

array([0, 0, 0, ..., 0, 0, 0])

In [87]:
from sklearn.metrics import accuracy_score, classification_report

In [88]:
dtc_accuracy = accuracy_score(y_test, dtc_prediction)
dtc_accuracy

0.814262023217247

In [89]:
print(classification_report(y_test, dtc_prediction))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88      6842
           1       0.62      0.61      0.62      2203

    accuracy                           0.81      9045
   macro avg       0.75      0.75      0.75      9045
weighted avg       0.81      0.81      0.81      9045

In [90]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(max_depth=10)
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=10)

In [91]:
rfc_prediction = rfc.predict(X_test)

In [92]:
rfc_accuracy = accuracy_score(y_test, rfc_prediction)
rfc_accuracy

0.8603648424543947

In [93]:
print(classification_report(y_test, rfc_prediction))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91      6842
           1       0.81      0.56      0.66      2203

    accuracy                           0.86      9045
   macro avg       0.84      0.76      0.79      9045
weighted avg       0.86      0.86      0.85      9045

In [94]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [96]:
from sklearn.svm import SVC

svm_model = SVC(kernel='linear')
svm_model.fit(X_train_scaled, y_train)
svm_prediction = svm_model.predict(X_test_scaled)

In [98]:
svm_accuracy = accuracy_score(y_test, svm_prediction)
svm_accuracy

0.8524046434494196

In [99]:
print(classification_report(y_test, svm_prediction))

              precision    recall  f1-score   support

           0       0.87      0.94      0.91      6842
           1       0.76      0.58      0.66      2203

    accuracy                           0.85      9045
   macro avg       0.82      0.76      0.78      9045
weighted avg       0.85      0.85      0.85      9045